CREATE DATABASE IF NOT EXISTS wp;
CREATE USER IF NOT EXISTS abittel@'%' IDENTIFIED BY "abittel42";
ALTER USER 'root'@'localhost' IDENTIFIED BY 'MariaDB42';
GRANT ALL PRIVILEGES ON wp.* TO 'abittel'@'%';
FLUSH PRIVILEGES;
