CREATE DATABASE IF NOT EXISTS wp;
CREATE USER IF NOT EXISTS 'user_wp'@'%' IDENTIFIED BY 'WordPress42';
ALTER USER 'root'@'localhost' IDENTIFIED BY 'MariaDB42';
GRANT ALL PRIVILEGES ON wp.* TO 'user_wp'@'%';
FLUSH PRIVILEGES;
