version: '3'
services:
  mariadb:
    build: ./mariadb
    container_name: mariadb
    ports: 
      - 3306:3306
    restart: unless-stopped
  wordpress:
    build: ./wordpress
    container_name: wordpress
    ports: 
      - 9000:9000
    restart: unless-stopped
  nginx:
    build: ./nginx
    container_name: nginx 
    ports: 
      - 80:80
    restart: unless-stopped

